export const GET_STATIONS = "GET_STATIONS";
export const STATIONS_LOADING = "STATIONS_LOADING";

export const GET_ARRIVING_TRAINS_BY_STATION = "GET_ARRIVING_TRAINS_BY_STATION";
export const GET_DEPARTING_TRAINS_BY_STATION =
  "GET_DEPARTING_TRAINS_BY_STATION";
export const GET_TRAINS_BY_STATION = "GET_TRAINS_BY_STATION";
export const TRAINS_LOADING = "TRAINS_LOADING";
